# vhr-toolkit combined container

# Arguments to pass to the image
ARG VERSION=latest
ARG FROM_IMAGE=nasanccs/vhr-cloudmask

# Import RAPIDS container as the BASE Image (cuda base image)
FROM ${FROM_IMAGE}:${VERSION}

# Ubuntu needs noninteractive to be forced
ENV DEBIAN_FRONTEND=noninteractive
ENV CPLUS_INCLUDE_PATH="/usr/include/gdal"
ENV C_INCLUDE_PATH="/usr/include/gdal"
ENV PROJ_LIB="/usr/share/proj"
ENV SM_FRAMEWORK="tf.keras"
ENV PYTHONPATH="/usr/local/lib/python3.8/dist-packages"
ENV PYTHONPATH="$PYTHONPATH:/usr/local/ilab"

# 7/19/24 - Combine PYTHONPATH for all 3 apps
ENV PYTHONPATH="$PYTHONPATH:/usr/local/ilab/vhr-cloudmask:/usr/local/ilab/evhr:/usr/local/ilab/core:/usr/local/ilab/srlite/srlite:/usr/local/ilab/srlite"
ENV PYTHONPATH="$PYTHONPATH:/opt/DgStereo/pygeotools:/opt/DgStereo/dgtools"
ENV PYTHONPATH="$PYTHONPATH:/opt/DgStereo/pygeotools:/opt/DgStereo/dgtools"
ENV PATH="$PATH:/opt/DgStereo/dgtools:/opt/DgStereo/pygeotools:/opt/DgStereo/dgtools/dgtools:/opt/StereoPipeline/bin:/opt/DgStereo/evhr"
ENV REDIS_PORT="6379"

# System dependencies
RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get -y install \
        build-essential \
        # EVHR system dependencies
        parallel \
        libdatetime-perl \
        gawk \
        util-linux \
        bc \
        # SRLite system dependencies
        python3-tk \
        tk-dev \
        libgdbm-dev \
        libc6-dev \
        libbz2-dev \
        libffi-dev \
        zlib1g-dev \
        liblzma-dev \
        libgirepository1.0-dev \
        libcairo2-dev \
        pkg-config \
        python3-dev \
        gir1.2-gtk-3.0 && \
    apt-get -y autoremove && \
    rm -rf /var/cache/apt /var/lib/apt/lists/*

#    PROJECT_PATH="/usr/local/ilab"
#    mkdir -p ${PROJECT_PATH}
#    STEREO_URL="https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/2.7.0/StereoPipeline-2.7.0-2020-07-29-x86_64-Linux.tar.bz2"

    #*******************************************************************************
    # EVHR
    #-------------------------------------------------------------------------------
    # EVHR System Dependencies
    #-------------------------------------------------------------------------------

#    wget $STEREO_URL -O /opt/StereoPipeline.tar.bz2 && cd /opt
#    tar -jxf StereoPipeline.tar.bz2 && rm /opt/StereoPipeline.tar.bz2
#    mv /opt/StereoPipeline* /opt/StereoPipeline

    #*** 7/19/24 -  REDIS and CELERY Dependencies
#    python -m pip install redis
#    python -m pip install celery[redis]

#    #-------------------------------------------------------------------------------
#    # EVHR DEM Dependencies-
#    #------------------------------------------------------------------------------
#    mkdir /opt/DgStereo
#    git clone https://gitlab.nccs.nasa.gov/cisto-ilab/evhr/dgtools.git /opt/DgStereo/dgtools
#    git clone https://gitlab.nccs.nasa.gov/cisto-ilab/evhr/imview.git /opt/DgStereo/imview
#    git clone https://gitlab.nccs.nasa.gov/cisto-ilab/evhr/pygeotools.git /opt/DgStereo/pygeotools
#    git clone https://gitlab.nccs.nasa.gov/cisto-ilab/evhr/evhr-dem.git /opt/DgStereo/evhr
#    printf "crane103\ncrane104\ncrane105\ncrane106\n\n" > /opt/DgStereo/nodeList.txt
#    chmod 755 -R /opt/*
#    python -m pip install 2to3 psycopg2-binary
#    2to3 -w /opt/DgStereo
#    chmod +wx /lib/x86_64-linux-gnu/libc.so.6

#    #-------------------------------------------------------------------------------
#    # EVHR git clone
#    #-------------------------------------------------------------------------------
#    # RECOMMENDED LOCATION - CURRENTLY INCLUDED IN CORE
#    git clone --single-branch --branch main https://github.com/nasa-nccs-hpda/core.git \
#    	${PROJECT_PATH}/core
#    git clone --single-branch --branch main https://github.com/nasa-nccs-hpda/evhr.git \
#		${PROJECT_PATH}/evhr
#    chmod a+rwx -R ${PROJECT_PATH}/*
#    
#    #******************************************************************************#

#    #******************************************************************************
#    # SR-Lite
#    #-------------------------------------------------------------------------------
#    # SR-Lite System Dependencies
#    #-------------------------------------------------------------------------------

#    #-------------------------------------------------------------------------------
#    # SR-Lite Git Dependencies
#    #-------------------------------------------------------------------------------
#    #pip3 install --upgrade pygeotools
#    #7/19/24 - plotnine uninstalls the original numpy 1.22 and installs numpy 1.24 which breaks the srlite run?
#    #pip3 install --upgrade plotnine
#    pip3 install plotnine==0.10.1
#    pip3 install --upgrade pylr2
#    # RECOMMENDED LOCATION - CURRENTLY INCLUDED IN CORE
#    git clone --single-branch --branch main https://github.com/nasa-nccs-hpda/srlite.git \
#        	${PROJECT_PATH}/srlite
#    chmod a+rwx -R ${PROJECT_PATH}/*
    
#    #******************************************************************************
#    # CCDC 
#    #-------------------------------------------------------------------------------
#    # CCDC System Dependencies
#    #-------------------------------------------------------------------------------


# Pip
# RUN pip install \
#    scipy \


HEALTHCHECK NONE
ENTRYPOINT []
CMD ["/bin/bash"]

